<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.cloud</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-consulting-api</module>
        <module>yudao-module-consulting-server</module>
    </modules>
    <artifactId>yudao-module-consulting</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        consulting 模块，餐饮咨询业务。
        例如说：客户档案、咨询项目、诊断报告、健康度评分
    </description>
</project>
