<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.cloud</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-restaurant-api</module>
        <module>yudao-module-restaurant-server</module>
    </modules>
    <artifactId>yudao-module-restaurant</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        restaurant 模块，餐饮垂直业务。
        例如说：菜品管理、桌台管理、订单、KDS厨房显示、库存、厨打小票
    </description>
</project>
